services:
  fitnessrecommendation:
    build:
      context: .
    container_name: fitnessrecommendation-service
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      - USER_SERVICE_URL=http://host.docker.internal:5001/user
      - ACTIVITY_LOG_URL=http://host.docker.internal:5030/activity
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3