services:
  user-service:
    image: lynnnnnno/user-service:1.0
    container_name: user-service
    ports:
      - "5001:5000"
    environment:
      - dbURL=mysql+mysqlconnector://root:root@host.docker.internal:8889/user 