version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activitylog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  activitylog:
    build:
      context: ./ActivityLog
    container_name: activitylog-service
    ports:
     - "5001:5000"
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: host.docker.internal  
      DB_NAME: activitylog

  notification:
    build:
      context: ./Notification
    container_name: notification-service
    ports:
      - "5002:5000"
    restart: unless-stopped

  leaderboards:
    build:
      context: ./Leaderboards
    container_name: leaderboards-service
    ports:
      - "5003:5000"
    restart: unless-stopped

  user:
    build:
      context: ./User
    container_name: user-service
    ports:
      - "5004:5000"
    restart: unless-stopped

volumes:
  mysql_data:
