version: "3.9"

services:
  activitylog:
    build:
      context: .
    container_name: activitylog-service
    ports:
      - "5030:5030"
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: host.docker.internal
      DB_NAME: activitylog
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-activitylog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activitylog
    ports:
      - "3309:3306"
    volumes:
      - activitylog_mysql_data:/var/lib/mysql
      - ./activitylog.sql:/docker-entrypoint-initdb.d/activitylog.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  activitylog_mysql_data:
