#NOT IN USE (FOR TESTING PURPOSES)
services:
  monthly-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    command: python main.py
