#NOT IN USE (FOR TESTING PURPOSES)
services:
 leaderboards:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: leaderboards
   ports:
     - "5005:5005"
   environment:
     - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/leaderboards
     - REDIS_HOST=redis
     - REDIS_PORT=6379
   depends_on:
     - redis
     - mysql

 redis:
   image: redis:alpine
   container_name: leaderboards-redis
   ports:
     - "6379:6379"

 mysql:
   image: mysql:8.0
   container_name: leaderboards-mysql
   ports:
     - "3307:3306"
   restart: always
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=leaderboards
   volumes:
     - leaderboards_mysql_data:/var/lib/mysql
     - ./leaderboards.sql:/docker-entrypoint-initdb.d/leaderboards.sql
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  leaderboards_mysql_data: