services:
 leaderboards:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: leaderboards
   ports:
     - "5005:5005"
   environment:
     - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/leaderboards
     - REDIS_HOST=redis
     - REDIS_PORT=6379
   depends_on:
     - redis
     - mysql

 redis:
   image: redis:alpine
   container_name: leaderboards-redis
   ports:
     - "6379:6379"

 mysql:
   image: mysql:8.0
   container_name: leaderboards-mysql
   ports:
     - "3307:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=leaderboards
     - MYSQL_USER=is213
     - MYSQL_PASSWORD=is213
   volumes:
     - ./leaderboards.sql:/docker-entrypoint-initdb.d/leaderboards.sql