services:
 leaderboards:
   image: garrikyx/leaderboards:1.0
   container_name: leaderboards
   ports:
     - "5000:5000"
   environment:
     - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/leaderboards